import {
  Utensils,
  Plane,
  ShoppingCart,
  Fuel,
  Tv,
  Globe,
  Bus,
  Pill,
  Hammer,
  Ticket,
  BedDouble,
  PlaneTakeoff,
  Car,
  CircleDot,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  utensils: Utensils,
  plane: Plane,
  "shopping-cart": ShoppingCart,
  fuel: Fuel,
  tv: Tv,
  globe: Globe,
  bus: Bus,
  pill: Pill,
  hammer: Hammer,
  ticket: Ticket,
  "bed-double": BedDouble,
  "plane-takeoff": PlaneTakeoff,
  car: Car,
  "circle-dot": CircleDot,
};

export const CATEGORY_COLORS: Record<string, string> = {
  dining: "#ef4444",
  travel: "#3b82f6",
  groceries: "#22c55e",
  gas: "#f59e0b",
  streaming: "#8b5cf6",
  online_shopping: "#06b6d4",
  transit: "#64748b",
  drugstores: "#ec4899",
  home_improvement: "#78716c",
  entertainment: "#a855f7",
  hotels: "#0ea5e9",
  flights: "#3b82f6",
  car_rental: "#14b8a6",
  other: "#9ca3af",
};
