export type TransferPartner = {
  name: string;
  ratio: string;
  type: "airline" | "hotel";
};

export const TRANSFER_PARTNERS: Record<string, TransferPartner[]> = {
  Chase: [
    { name: "United MileagePlus", ratio: "1:1", type: "airline" },
    { name: "Southwest Rapid Rewards", ratio: "1:1", type: "airline" },
    { name: "British Airways Executive Club", ratio: "1:1", type: "airline" },
    { name: "Air France/KLM Flying Blue", ratio: "1:1", type: "airline" },
    { name: "Singapore KrisFlyer", ratio: "1:1", type: "airline" },
    { name: "Korean Air SKYPASS", ratio: "1:1", type: "airline" },
    { name: "Aer Lingus AerClub", ratio: "1:1", type: "airline" },
    { name: "Iberia Plus", ratio: "1:1", type: "airline" },
    { name: "Virgin Atlantic Flying Club", ratio: "1:1", type: "airline" },
    { name: "World of Hyatt", ratio: "1:1", type: "hotel" },
    { name: "IHG One Rewards", ratio: "1:1", type: "hotel" },
    { name: "Marriott Bonvoy", ratio: "1:1", type: "hotel" },
  ],
  "American Express": [
    { name: "Delta SkyMiles", ratio: "1:1", type: "airline" },
    { name: "British Airways Executive Club", ratio: "1:1", type: "airline" },
    { name: "Air France/KLM Flying Blue", ratio: "1:1", type: "airline" },
    { name: "Singapore KrisFlyer", ratio: "1:1", type: "airline" },
    { name: "ANA Mileage Club", ratio: "1:1", type: "airline" },
    { name: "Avianca LifeMiles", ratio: "1:1", type: "airline" },
    { name: "Cathay Pacific Asia Miles", ratio: "1:1", type: "airline" },
    { name: "Emirates Skywards", ratio: "1:1", type: "airline" },
    { name: "Etihad Guest", ratio: "1:1", type: "airline" },
    { name: "HawaiianMiles", ratio: "1:1", type: "airline" },
    { name: "Iberia Plus", ratio: "1:1", type: "airline" },
    { name: "JetBlue TrueBlue", ratio: "250:200", type: "airline" },
    { name: "Hilton Honors", ratio: "1:2", type: "hotel" },
    { name: "Marriott Bonvoy", ratio: "1:1", type: "hotel" },
    { name: "Choice Privileges", ratio: "1:1", type: "hotel" },
  ],
  Citi: [
    { name: "Avianca LifeMiles", ratio: "1:1", type: "airline" },
    { name: "Turkish Miles&Smiles", ratio: "1:1", type: "airline" },
    { name: "Singapore KrisFlyer", ratio: "1:1", type: "airline" },
    { name: "Air France/KLM Flying Blue", ratio: "1:1", type: "airline" },
    { name: "Cathay Pacific Asia Miles", ratio: "1:1", type: "airline" },
    { name: "ANA Mileage Club", ratio: "1:1", type: "airline" },
    { name: "Etihad Guest", ratio: "1:1", type: "airline" },
    { name: "Eva Air Infinity MileageLands", ratio: "1:1", type: "airline" },
    { name: "Qantas Frequent Flyer", ratio: "1:1", type: "airline" },
    { name: "Thai Royal Orchid Plus", ratio: "1:1", type: "airline" },
    { name: "IHG One Rewards", ratio: "1:1.5", type: "hotel" },
    { name: "Wyndham Rewards", ratio: "1:1.5", type: "hotel" },
  ],
  "Capital One": [
    { name: "Air Canada Aeroplan", ratio: "1:1", type: "airline" },
    { name: "Avianca LifeMiles", ratio: "1:1", type: "airline" },
    { name: "British Airways Executive Club", ratio: "1:1", type: "airline" },
    { name: "Cathay Pacific Asia Miles", ratio: "1:1", type: "airline" },
    { name: "Finnair Plus", ratio: "1:1", type: "airline" },
    { name: "Air France/KLM Flying Blue", ratio: "1:1", type: "airline" },
    { name: "Singapore KrisFlyer", ratio: "1:1", type: "airline" },
    { name: "TAP Portugal Miles&Go", ratio: "1:1", type: "airline" },
    { name: "Turkish Miles&Smiles", ratio: "1:1", type: "airline" },
    { name: "Wyndham Rewards", ratio: "1:1", type: "hotel" },
    { name: "Choice Privileges", ratio: "1:1", type: "hotel" },
  ],
  Bilt: [
    { name: "Alaska Mileage Plan", ratio: "1:1", type: "airline" },
    { name: "American AAdvantage", ratio: "1:1", type: "airline" },
    { name: "Air Canada Aeroplan", ratio: "1:1", type: "airline" },
    { name: "Air France/KLM Flying Blue", ratio: "1:1", type: "airline" },
    { name: "British Airways Executive Club", ratio: "1:1", type: "airline" },
    { name: "Cathay Pacific Asia Miles", ratio: "1:1", type: "airline" },
    { name: "Emirates Skywards", ratio: "1:1", type: "airline" },
    { name: "Singapore KrisFlyer", ratio: "1:1", type: "airline" },
    { name: "Turkish Miles&Smiles", ratio: "1:1", type: "airline" },
    { name: "United MileagePlus", ratio: "1:1", type: "airline" },
    { name: "Virgin Atlantic Flying Club", ratio: "1:1", type: "airline" },
    { name: "World of Hyatt", ratio: "1:1", type: "hotel" },
    { name: "IHG One Rewards", ratio: "1:1", type: "hotel" },
    { name: "Marriott Bonvoy", ratio: "1:1", type: "hotel" },
  ],
  "Wells Fargo": [
    { name: "Air France/KLM Flying Blue", ratio: "1:1", type: "airline" },
    { name: "Avianca LifeMiles", ratio: "1:1", type: "airline" },
    { name: "British Airways Executive Club", ratio: "1:1", type: "airline" },
    { name: "Iberia Plus", ratio: "1:1", type: "airline" },
    { name: "Turkish Miles&Smiles", ratio: "1:1", type: "airline" },
  ],
};
