// This file is auto-generated by Supabase CLI.
// Run: npm run gen:types (after setting YOUR_PROJECT_ID in package.json)
//
// Until generated, this exports a permissive Database type that keeps
// the Supabase clients fully functional without breaking existing type inference.

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Database = any;
